name: tests-auth

on:
  pull_request:
    paths:
      - "authService/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: cd authService && npm install && npm run test
